name: AU Packages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 */8 * * *' # every 8 hours at 5 minutes past the hour
  workflow_dispatch:

jobs:
  auto-update:
    # Auto Update
    uses: ./.github/workflows/auto-update.yml
    with:      
      workflow_name: ${{ github.workflow }}
      gist_id: 1bef29d6b69a03cb02702cbfb67e106e
      gist_id_test: 8aaa677a197c99e5eca431489a964ace
    secrets:
      personal_access_token: ${{ secrets.GH_API_KEY }}
      chocolatey_api_key: ${{ secrets.API_KEY }}